### ISSUE TITLE
Suggestion to improve experience for multi-namespace term change template

### ISSUE THREAD

**Issue by tucotuco** [tdwg/rs.tdwg.org#40]
@baskaufs  By using a line within the content to create a new "section" within the document, the csv is not visible as a spreadsheet in GitHub, which would be useful. Right now, for example, https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/terms-changes-2020-08.csv shows the message "We can make this file beautiful and searchable if this error is corrected: It looks like row 11 should actually have 9 columns, instead of 1. in line 10." The same issue might apply in other environments when trying to hand edit the file. A solution could be to add a column for the namespace abbreviation, and just have it part of every record.

**Comment by baskaufs** [comment]
The problem here is that each namespace has to be processed separately. Having them together in the template is just intended to make things simpler for the vocabulary developer/maintainers. The burden is shifted from the vocabulary developer/maintainers to the infrastructure maintainers who have to split the submitted spreadsheet into to separate CSVs, then run them through the process separately. One could have a column for the namespace, but the spreadsheet would still have to be split up.

It would be possible to have an "all in one" solution that could handle multiple namespaces in a single spreadsheet, but that would require making the processing script more complicated, and it's already pretty complicated now. I was anticipating that this case of having to split up sections for different namespaces would be relatively uncommon in the maintenance of vocabularies that are already set up, since changes to borrowed vocabularies would probably be somewhat infrequent. In the case where changes were made to only a single namespace (i.e. the TDWG minted one), the simpler example spreadsheet could just be used.

**Comment by tucotuco** [comment]
OK, I understand.
