### ISSUE TITLE
Term replacement

### ISSUE THREAD

**Issue by tucotuco** [tdwg/rs.tdwg.org#41]
@baskaufs How would one make an entry in the term change document if one term is deprecated in favor of a different one with different localName? This has happened in the past, such as when  http://rs.tdwg.org/dwc/terms/version/acceptedNameUsageID-2009-09-21 replaced http://rs.tdwg.org/dwc/terms/version/acceptedTaxonID-2009-08-24.

**Comment by baskaufs** [comment]
@tucotuco Term replacement/deprecation is a much more complex process that requires manual steps that aren't handled automatically by the script. I have some notes on deprecation at the top of the [Jupyter notebook with detailed notes](https://github.com/tdwg/rs.tdwg.org/blob/master/process/process_rs_tdwg_org.ipynb). As I note there, I believe that we should really get out of the business of changing term localNames because it contributes to the instability of the vocabulary. That is also the reason why I'm in favor of using term labels for public presentation since they can be changed without "breaking" anything. 

Nevertheless, it is bound to happen and I have fairly detailed notes in that cell explaining the steps that need to be taken when a term needs to be deprecated.
